name: PO Token Uretici (Manuel)
on: workflow_dispatch

jobs:
  uret:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Hazirlik
        uses: actions/checkout@v3

      - name: Python Kurulumu
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Scripti Indir ve Calistir
        run: |
          git clone https://github.com/IV-ORG/youtube-trusted-session-generator.git temp_generator
          cd temp_generator
          pip install -r requirements.txt
          python main.py
